source 'https://rubygems.org'
ruby '2.2.2'

# To install all these gems, run "gem install bundler", then "bundle install".

gem 'minitest', '5.15.0'
gem 'minitest-reporters', '1.7.1'
gem 'simplecov', '0.17.1'
gem 'simplecov-cobertura', '1.4.2'
