name: Build and publish the Ruby package

on:
  release:
    types: [published]

jobs:
  build_gem:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code from repo
      uses: actions/checkout@v4

    - name: Log into GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build devcontainer and build the package
      uses: devcontainers/ci@v0.3
      with:
        imageName: ghcr.io/cfe-lab/gotoh_devcontainer
        cacheFrom: ghcr.io/cfe-lab/gotoh_devcontainer
        runCmd: cd /workspaces/gotoh/ruby && bash build_gem.bash
        env: |
          CFE_GOTOH_VERSION=${{ github.ref_name }}

    - name: Publish gem to Github Packages
      run: |
        mkdir -p $HOME/.gem
        touch $HOME/.gem/credentials
        chmod 0600 $HOME/.gem/credentials
        printf -- "---\n:github: Bearer ${GEM_HOST_API_KEY}\n" > $HOME/.gem/credentials
        gem push --KEY github --host https://rubygems.pkg.github.com/${OWNER} *.gem
      env:
        GEM_HOST_API_KEY: ${{ secrets.GITHUB_TOKEN }}
        OWNER: ${{ github.repository_owner }}
