name: Build the Ruby package

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code from repo
      uses: actions/checkout@v3

    - name: Log into GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build devcontainer and build the package
      uses: devcontainers/ci@v0.3
      with:
        imageName: ghcr.io/cfe-lab/gotoh_devcontainer
        cacheFrom: ghcr.io/cfe-lab/gotoh_devcontainer
        runCmd: cd /workspaces/gotoh/ruby && bash build_gem.bash
        env: |
          CFE_GOTOH_VERSION=${{ github.ref_name }}
