name: Automated Tests

on: ["push"]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code from repo
      uses: actions/checkout@v3

    - name: Log into GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build devcontainer and run tests
      uses: devcontainers/ci@v0.3
      with:
        imageName: ghcr.io/cfe-lab/gotoh_devcontainer
        cacheFrom: ghcr.io/cfe-lab/gotoh_devcontainer
        runCmd: cd ${{ github.workspace }}/ruby && rake test

    - name: Upload coverage reports to Codecov with GitHub Action
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        root_dir: ${{ github.workspace }}
        files: ${{ github.workspace }}/ruby/coverage/coverage.xml
